os: linux
language: rust

rust:
  - beta
  - stable
  - 1.38.0

before_script:
  - rustup component add rustfmt
  - rustup target add thumbv7em-none-eabihf

script:
  - cargo fmt -- --check
  - cargo test
  - cargo build --target thumbv7em-none-eabihf
